# Generated by Django 3.2.3 on 2021-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ref_code',
            field=models.CharField(default='49d2e01459', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='sharing_increased',
            field=models.IntegerField(default=1),
        ),
    ]
