# Generated by Django 3.2.6 on 2021-08-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='defaultUser.png', null=True, upload_to='')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('ref_code', models.CharField(default='7a59532c69', max_length=10)),
                ('referred_by_up', models.CharField(blank=True, max_length=20, null=True)),
                ('referred_by_down', models.CharField(blank=True, max_length=20, null=True)),
                ('has_helped_up', models.BooleanField(default=False)),
                ('has_helped_down', models.BooleanField(default=False)),
                ('sharing_increased', models.IntegerField(default=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
